project:
  type: site
  output-dir: docs

site:
  title: "Literature 📚 "
  subtitle: "Literature Overview"
  navbar:
    search: true
  page-navigation: true
  page-footer: 
    left: '© 2022, Patrick Altmeyer'
    right: 
      - icon: house
        href: https://www.paltmeyer.com/
      - icon: github
        href: https://github.com/pat-alt
      - icon: twitter
        href: https://twitter.com/paltmey
      - icon: medium
        href: https://medium.com/\@patrick.altmeyer
  repo-url: https://github.com/pat-alt/tai
  repo-actions: [issue]

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

bibliography: bib.bib



